# Generated by Django 5.1.4 on 2025-03-04 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitems",
            old_name="psition",
            new_name="position",
        ),
    ]
