# Generated by Django 5.1.4 on 2025-03-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_category_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
