# Generated by Django 5.1.4 on 2025-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_article_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="featured_image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
