# Generated by Django 5.1.4 on 2025-03-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_author_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
