# Generated by Django 5.1.4 on 2025-03-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0006_alter_author_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
