# Generated by Django 5.1.4 on 2025-03-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0007_author_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
